"""Create company models

Revision ID: 09e71c7acfee
Revises: 
Create Date: 2023-11-08 23:08:32.087748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e71c7acfee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('staff_units_id', sa.Integer(), nullable=True),
    sa.Column('is_acting', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['staff_units_id'], ['staff_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_staff_units_id'), 'assignment', ['staff_units_id'], unique=False)
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_division_id', sa.Integer(), nullable=True),
    sa.Column('unit_head_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['unit_head_id'], ['staff_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_parent_division_id'), 'division', ['parent_division_id'], unique=False)
    op.create_index(op.f('ix_division_unit_head_id'), 'division', ['unit_head_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replacement_id', sa.Integer(), nullable=True),
    sa.Column('substitute_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['replacement_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['substitute_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acting_division_id'), 'acting', ['division_id'], unique=False)
    op.create_index(op.f('ix_acting_replacement_id'), 'acting', ['replacement_id'], unique=False)
    op.create_index(op.f('ix_acting_substitute_id'), 'acting', ['substitute_id'], unique=False)
    op.create_table('staff_unit_division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_unit_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['staff_unit_id'], ['staff_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_unit_division_division_id'), 'staff_unit_division', ['division_id'], unique=False)
    op.create_index(op.f('ix_staff_unit_division_staff_unit_id'), 'staff_unit_division', ['staff_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_unit_division_staff_unit_id'), table_name='staff_unit_division')
    op.drop_index(op.f('ix_staff_unit_division_division_id'), table_name='staff_unit_division')
    op.drop_table('staff_unit_division')
    op.drop_index(op.f('ix_acting_substitute_id'), table_name='acting')
    op.drop_index(op.f('ix_acting_replacement_id'), table_name='acting')
    op.drop_index(op.f('ix_acting_division_id'), table_name='acting')
    op.drop_table('acting')
    op.drop_table('user')
    op.drop_index(op.f('ix_division_unit_head_id'), table_name='division')
    op.drop_index(op.f('ix_division_parent_division_id'), table_name='division')
    op.drop_table('division')
    op.drop_index(op.f('ix_assignment_staff_units_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_table('staff_unit')
    op.drop_table('role')
    op.drop_table('employee')
    # ### end Alembic commands ###
